on:
    push:
        paths-ignore:
            - "**/README.md"
            - "**/build_linux.yml"
    pull_request:

name: Build on Windows
jobs:
    build-windows:
        runs-on: windows-latest
        strategy:
            fail-fast: false
            matrix:
                language: ["cpp"]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Compile
              run: "mkdir build && cd build && cmake ../example/simple && cmake --build . --config Release"