on:
    push:
        paths-ignore:
            - "**/README.md"
            - "**/build_windows.yml"
    pull_request:

name: Build on Linux
jobs:
    build-linux:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                language: ["cpp"]

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Install build dependencies
              run: "sudo apt-get install git build-essential cmake libappindicator3-dev"

            - name: Compile
              run: "mkdir build && cd build && cmake ../example/simple && cmake --build . --config Release"